model:
  name: shiftfuse_zero_small_late_efficient
  variant: small_late_efficient_bb
  num_classes: 60
  use_se: false
  use_k3_adj: false
  multi_gcn: true
  use_adyn: false
  drop_path_rate: 0.10
  dropout: 0.10
