model:
  name: shiftfuse_zero_nano_lite_efficient
  variant: nano_lite_efficient
  num_classes: 60
  use_se: false
  use_k3_adj: false
  multi_gcn: true
  use_adyn: false
  drop_path_rate: 0.05
  dropout: 0.10
